### ISSUE TITLE
[Question] Not sure if closing the connection here is premature

### ISSUE THREAD

**Issue by chrischongyj** [HypotheticalWhale/MDP-Application#11]
https://github.com/HypotheticalWhale/MDP-Application/blob/b5c10ecc9caff4cf7fa4fded073b9390112799db/app/src/main/java/com/example/mdpapplication/BluetoothConnectionHelper.java#L517

**Comment by chrischongyj** [comment]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/39231238/154861367-f0340371-2593-43ca-861b-703819e01d0f.png">
its calling close() after connect()

**Comment by soulpower11** [comment]
Hmm, maybe that is an issue, 
I changed it to how it is done in the official example in the Bluetooth doc. There is a socket.close(); too but it's in a switch case. Maybe we can try it later
